-- 코드를 입력하세요
SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES 
  FROM (
  SELECT
      FOOD_TYPE, 
      REST_ID, 
      REST_NAME, 
      FAVORITES, 
      RANK() over (PARTITION BY FOOD_TYPE ORDER BY FAVORITES DESC) AS rn
    FROM REST_INFO
  ) a
 WHERE a.rn <= 1
 ORDER BY FOOD_TYPE DESC ;

 