-- 코드를 입력하세요
SELECT DISTINCT
    hist.CAR_ID,
    CASE
        WHEN c.cnt > 0 THEN '대여중'
        ELSE '대여 가능'
    END AVAILABILITY
 FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY hist
 LEFT OUTER JOIN (
       SELECT CAR_ID, COUNT(HISTORY_ID) AS cnt 
         FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
        WHERE STR_TO_DATE('2022-10-16','%Y-%m-%d') BETWEEN START_DATE AND END_DATE
        GROUP BY CAR_ID
    ) c
   ON hist.CAR_ID = c.CAR_ID
GROUP BY 1,2
ORDER BY hist.CAR_ID DESC ;

