-- 코드를 입력하세요
SELECT
  users.USER_ID, users.NICKNAME, SUM(board.PRICE) AS TOTAL_SALES
  FROM USED_GOODS_USER users
 INNER JOIN USED_GOODS_BOARD  board
    ON users.USER_ID = board.WRITER_ID
 WHERE board.STATUS = 'DONE'
 GROUP BY 1,2
HAVING TOTAL_SALES >= '700000'
 ORDER BY TOTAL_SALES ASC ;
 