-- 코드를 입력하세요
SELECT
    MONTH(hist.START_DATE) AS MONTH, 
    hist.CAR_ID, 
    COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY hist
WHERE hist.CAR_ID IN (
    SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE YEAR(START_DATE) = 2022
      AND MONTH(START_DATE) >= 8 
      AND MONTH(START_DATE) <= 10 
    GROUP BY CAR_ID
   HAVING COUNT(CAR_ID) >= 5
)
  AND YEAR(START_DATE) = 2022
  AND MONTH(START_DATE) >= 8 
  AND MONTH(START_DATE) <= 10 
GROUP BY MONTH, CAR_ID
HAVING RECORDS >= 1
ORDER BY MONTH ASC, CAR_ID DESC 