-- 코드를 입력하세요
SELECT
    BOOK_ID, DATE_FORMAT(PUBLISHED_DATE, '%Y-%m-%d') AS PUBLISHED_DATE
  FROM BOOK
 WHERE YEAR(PUBLISHED_DATE) = '2021'
   # AND PUBLISHED_DATE >= STR_TO_DATE('2021-01-01 00:00:00', '%Y-%m-%d %H:%i:%s') 
   # AND PUBLISHED_DATE < STR_TO_DATE('2021-12-31 23:59:59', '%Y-%m-%d %H:%i:%s')
   AND CATEGORY = '인문'
 ORDER BY PUBLISHED_DATE ASC
   ;