-- 코드를 입력하세요
SELECT
       b.CATEGORY, 
       SUM(bs.SALES) AS TOTLA_SALES
  FROM BOOK b
 INNER JOIN BOOK_SALES bs
    ON b.BOOK_ID = bs.BOOK_ID
 WHERE YEAR(bs.SALES_DATE) = 2022
   AND MONTH(bs.SALES_DATE) = 1
 GROUP BY 1
 ORDER BY 1;